# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/videoconnector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/videoconnector.proto',
  package='videoconnector',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aproto/videoconnector.proto\x12\x0evideoconnector\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x0fRegisterRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\"\x1e\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x11UnRegisterRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\x05\"\x14\n\x12UnRegisterResponse\"s\n\x0e\x43ommandRequest\x12\x33\n\x0f\x63lientTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11\x63onnectorHostname\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\x05\"q\n\x0b\x43ommandList\x12\x33\n\x0fserverTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x08\x63ommands\x18\x02 \x03(\x0e\x32\x1b.videoconnector.CommandType\"m\n\x14TransferImageRequest\x12\x33\n\x0f\x63lientTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\x0c\"H\n\x11ServerAckResponse\x12\x33\n\x0fserverTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\\\n\x11SourceInfoRequest\x12\x33\n\x0f\x63lientTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nsourceInfo\x18\x02 \x01(\t*d\n\x0b\x43ommandType\x12\t\n\x05NoNew\x10\x00\x12\x08\n\x04Stop\x10\x01\x12\n\n\x06Resume\x10\x02\x12\x13\n\x0fStopAndShutdown\x10\x03\x12\x0c\n\x08GetImage\x10\x04\x12\x11\n\rGetSourceInfo\x10\x05\x32\xc0\x03\n\x0eVideoConnector\x12S\n\x0eRegisterClient\x12\x1f.videoconnector.RegisterRequest\x1a .videoconnector.RegisterResponse\x12Y\n\x10UnRegisterClient\x12!.videoconnector.UnRegisterRequest\x1a\".videoconnector.UnRegisterResponse\x12I\n\nGetCommand\x12\x1e.videoconnector.CommandRequest\x1a\x1b.videoconnector.CommandList\x12Y\n\x11\x44\x65liverSourceInfo\x12!.videoconnector.SourceInfoRequest\x1a!.videoconnector.ServerAckResponse\x12X\n\rTransferImage\x12$.videoconnector.TransferImageRequest\x1a!.videoconnector.ServerAckResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='videoconnector.CommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NoNew', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Stop', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Resume', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='StopAndShutdown', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GetImage', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GetSourceInfo', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=739,
  serialized_end=839,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
NoNew = 0
Stop = 1
Resume = 2
StopAndShutdown = 3
GetImage = 4
GetSourceInfo = 5



_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='videoconnector.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='videoconnector.RegisterRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=114,
)


_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='videoconnector.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='videoconnector.RegisterResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=146,
)


_UNREGISTERREQUEST = _descriptor.Descriptor(
  name='UnRegisterRequest',
  full_name='videoconnector.UnRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='videoconnector.UnRegisterRequest.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='videoconnector.UnRegisterRequest.client_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=204,
)


_UNREGISTERRESPONSE = _descriptor.Descriptor(
  name='UnRegisterResponse',
  full_name='videoconnector.UnRegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=226,
)


_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='videoconnector.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientTimestamp', full_name='videoconnector.CommandRequest.clientTimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connectorHostname', full_name='videoconnector.CommandRequest.connectorHostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='videoconnector.CommandRequest.client_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=343,
)


_COMMANDLIST = _descriptor.Descriptor(
  name='CommandList',
  full_name='videoconnector.CommandList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverTimestamp', full_name='videoconnector.CommandList.serverTimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commands', full_name='videoconnector.CommandList.commands', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=458,
)


_TRANSFERIMAGEREQUEST = _descriptor.Descriptor(
  name='TransferImageRequest',
  full_name='videoconnector.TransferImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientTimestamp', full_name='videoconnector.TransferImageRequest.clientTimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='videoconnector.TransferImageRequest.client_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='videoconnector.TransferImageRequest.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=569,
)


_SERVERACKRESPONSE = _descriptor.Descriptor(
  name='ServerAckResponse',
  full_name='videoconnector.ServerAckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverTimestamp', full_name='videoconnector.ServerAckResponse.serverTimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=643,
)


_SOURCEINFOREQUEST = _descriptor.Descriptor(
  name='SourceInfoRequest',
  full_name='videoconnector.SourceInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientTimestamp', full_name='videoconnector.SourceInfoRequest.clientTimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sourceInfo', full_name='videoconnector.SourceInfoRequest.sourceInfo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=645,
  serialized_end=737,
)

_COMMANDREQUEST.fields_by_name['clientTimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COMMANDLIST.fields_by_name['serverTimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COMMANDLIST.fields_by_name['commands'].enum_type = _COMMANDTYPE
_TRANSFERIMAGEREQUEST.fields_by_name['clientTimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SERVERACKRESPONSE.fields_by_name['serverTimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SOURCEINFOREQUEST.fields_by_name['clientTimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE
DESCRIPTOR.message_types_by_name['UnRegisterRequest'] = _UNREGISTERREQUEST
DESCRIPTOR.message_types_by_name['UnRegisterResponse'] = _UNREGISTERRESPONSE
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['CommandList'] = _COMMANDLIST
DESCRIPTOR.message_types_by_name['TransferImageRequest'] = _TRANSFERIMAGEREQUEST
DESCRIPTOR.message_types_by_name['ServerAckResponse'] = _SERVERACKRESPONSE
DESCRIPTOR.message_types_by_name['SourceInfoRequest'] = _SOURCEINFOREQUEST
DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

UnRegisterRequest = _reflection.GeneratedProtocolMessageType('UnRegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNREGISTERREQUEST,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.UnRegisterRequest)
  })
_sym_db.RegisterMessage(UnRegisterRequest)

UnRegisterResponse = _reflection.GeneratedProtocolMessageType('UnRegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNREGISTERRESPONSE,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.UnRegisterResponse)
  })
_sym_db.RegisterMessage(UnRegisterResponse)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)

CommandList = _reflection.GeneratedProtocolMessageType('CommandList', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDLIST,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.CommandList)
  })
_sym_db.RegisterMessage(CommandList)

TransferImageRequest = _reflection.GeneratedProtocolMessageType('TransferImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERIMAGEREQUEST,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.TransferImageRequest)
  })
_sym_db.RegisterMessage(TransferImageRequest)

ServerAckResponse = _reflection.GeneratedProtocolMessageType('ServerAckResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERACKRESPONSE,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.ServerAckResponse)
  })
_sym_db.RegisterMessage(ServerAckResponse)

SourceInfoRequest = _reflection.GeneratedProtocolMessageType('SourceInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOURCEINFOREQUEST,
  '__module__' : 'proto.videoconnector_pb2'
  # @@protoc_insertion_point(class_scope:videoconnector.SourceInfoRequest)
  })
_sym_db.RegisterMessage(SourceInfoRequest)



_VIDEOCONNECTOR = _descriptor.ServiceDescriptor(
  name='VideoConnector',
  full_name='videoconnector.VideoConnector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=842,
  serialized_end=1290,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterClient',
    full_name='videoconnector.VideoConnector.RegisterClient',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UnRegisterClient',
    full_name='videoconnector.VideoConnector.UnRegisterClient',
    index=1,
    containing_service=None,
    input_type=_UNREGISTERREQUEST,
    output_type=_UNREGISTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCommand',
    full_name='videoconnector.VideoConnector.GetCommand',
    index=2,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_COMMANDLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeliverSourceInfo',
    full_name='videoconnector.VideoConnector.DeliverSourceInfo',
    index=3,
    containing_service=None,
    input_type=_SOURCEINFOREQUEST,
    output_type=_SERVERACKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TransferImage',
    full_name='videoconnector.VideoConnector.TransferImage',
    index=4,
    containing_service=None,
    input_type=_TRANSFERIMAGEREQUEST,
    output_type=_SERVERACKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIDEOCONNECTOR)

DESCRIPTOR.services_by_name['VideoConnector'] = _VIDEOCONNECTOR

# @@protoc_insertion_point(module_scope)
