# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: videoconnector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14videoconnector.proto\x12\x0evideoconnector\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n\x0e\x43ommandRequest\x12\x33\n\x0f\x63lientTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11\x63onnectorHostname\x18\x02 \x01(\t\"q\n\x0b\x43ommandList\x12\x33\n\x0fserverTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x08\x63ommands\x18\x02 \x03(\x0e\x32\x1b.videoconnector.CommandType\"m\n\x14TransferImageRequest\x12\x33\n\x0f\x63lientTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tcamera_id\x18\x02 \x01(\x03\x12\r\n\x05image\x18\x03 \x01(\x0c\"H\n\x11ServerAckResponse\x12\x33\n\x0fserverTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\\\n\x11SourceInfoRequest\x12\x33\n\x0f\x63lientTimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nsourceInfo\x18\x02 \x01(\t*d\n\x0b\x43ommandType\x12\t\n\x05NoNew\x10\x00\x12\x08\n\x04Stop\x10\x01\x12\n\n\x06Resume\x10\x02\x12\x13\n\x0fStopAndShutdown\x10\x03\x12\x0c\n\x08GetImage\x10\x04\x12\x11\n\rGetSourceInfo\x10\x05\x32\x90\x02\n\x0eVideoConnector\x12I\n\nGetCommand\x12\x1e.videoconnector.CommandRequest\x1a\x1b.videoconnector.CommandList\x12Y\n\x11\x44\x65liverSourceInfo\x12!.videoconnector.SourceInfoRequest\x1a!.videoconnector.ServerAckResponse\x12X\n\rTransferImage\x12$.videoconnector.TransferImageRequest\x1a!.videoconnector.ServerAckResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videoconnector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDTYPE._serialized_start=565
  _COMMANDTYPE._serialized_end=665
  _COMMANDREQUEST._serialized_start=73
  _COMMANDREQUEST._serialized_end=169
  _COMMANDLIST._serialized_start=171
  _COMMANDLIST._serialized_end=284
  _TRANSFERIMAGEREQUEST._serialized_start=286
  _TRANSFERIMAGEREQUEST._serialized_end=395
  _SERVERACKRESPONSE._serialized_start=397
  _SERVERACKRESPONSE._serialized_end=469
  _SOURCEINFOREQUEST._serialized_start=471
  _SOURCEINFOREQUEST._serialized_end=563
  _VIDEOCONNECTOR._serialized_start=668
  _VIDEOCONNECTOR._serialized_end=940
# @@protoc_insertion_point(module_scope)
